version: '3'
services:
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=production
    container_name: is212-g5t7-server
    restart: unless-stopped
    env_file: server/.env
    ports:
      - "3001:3001"
  client:
    build: ./client
    container_name: is212-g5t7-client
    restart: unless-stopped
    env_file: client/.env
    environment:
      - API_URL=http://localhost:3001
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
