export const skills = {
  sales: [
    'Product Knowledge',
    'Lead Qualification',
    'Lead Prospecting ',
    'Customer Needs Analysis',
    'Referral Marketing',
    'Contract Negotiation',
    'CRM Software (Salesforce, Hubspot, Zoho, Freshsales)',
    'POS Skills',
    'Cashier Skills',
  ],
  technology: [
    'Web Development',
    'Data Structures',
    'Security',
    'Machine Learning',
    'UX/UI',
    'Cloud Management',
    'Agile Development',
  ],
  marketing: [
    'SEO/SEM',
    'A/B Testing',
    'Social Media Marketing and Paid Social Media Advertising',
    'Sales Funnel Management',
    'CMS Tools',
    'Graphic Design Skills',
    'Email Marketing Skills',
    'Email Automation',
    'Data Visualization',
    'Typography',
    'Print Design',
    'Photography and Branding',
  ],
  admin: [
    'Data Entry',
    'Billing',
    'Scheduling',
    'Microsoft Office',
    'Shipping',
    'Salesforce',
  ],
};
